version: "3.7"
services:
    webserver:
        build:
            context: ./docker/development/nginx
        volumes:
            - ./:/var/www
        ports:
            - "81:81"

    fpm:
        build:
            context: ./docker/development
            dockerfile: fpm/Dockerfile
        volumes:
            - ./:/var/www
        environment:
            PHP_IDE_CONFIG: serverName=TEST

    cli:
        build:
            context: ./docker/development
            dockerfile: cli/Dockerfile
        volumes:
            - ./:/var/www

    postgres:
        image: postgres:14.3-alpine
        restart: always
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - "54321:5432"

    adminer:
        build:
            context: ./docker/development
            dockerfile: adminer/Dockerfile
        ports:
            - "8080:8080"

    node-cli:
        build:
            context: ./docker/development/node
        volumes:
            - ./:/var/www

networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 122.122.221.0/28

volumes:
    postgres:
